openapi : 3.0.0

info:
  title: social app
  description: a social app api for pratice.
  version: 0.1.9

servers:
  - url: https://localhost:4000/api/v1
    description:  Main (production) server
  - url: http://localhost:4000/api/v1
    description: Internal staging server for testing

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy: 
    get:
      summary:dummy api